[package]
name = "pokemon-battle-system"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
dotenvy = "0.15.7"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
